### ISSUE TITLE
Very first Discussions / Questions about the Project Admin

### ISSUE THREAD

**Issue by christoph-v** [christoph-v/spark#7]
**Describe the bug**
The SP-ARK project is still very fuzzy.

**To Reproduce**
1. Go to the homepage ([https://areasharpa.wordpress.com/spark](https://areasharpa.wordpress.com/spark))
2. Try to understand the project
3. It's at least time consuming, if not impossible

**Expected behavior**
The project should be understood within minutes

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: any
 - Browser [e.g. chrome, safari]: any
 - Version [e.g. 22] : any

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] any
 - OS: [e.g. iOS8.1] any
 - Browser [e.g. stock browser, safari] any
 - Version [e.g. 22] any

**Additional context**
What's the connex between SrrTrains and SP-ARK

**Comment by christoph-v** [comment]
As long as the project does not own a Wiki, nor any Fora or other smart communication facilities, I would SUGGEST TO DISCUSS THIS ISSUE JUST HERE IN THE COMMENTS OF THE ISSUE

**Comment by christoph-v** [comment]
Please add any question, suggestion, comment or improvement proposal here, if you like :-)

**Comment by coderextreme** [comment]
My game is pc.multiplayer (origins in playcanvas)

**Comment by christoph-v** [comment]
Hi John. Yes, I know.

The SP-ARK project's main goal is to "somehow" support the definition of a communication protocol for the X3D  Network Sensor node.

Additional goals could be defined by interest.

I am sure your game will be a precious source of inspiration and when a volunteer is found who starts to analyse your game, then we might find even more synergies :-)

**Comment by christoph-v** [comment]
And I corrected the typo :-)

**Comment by christoph-v** [comment]
Should we consider the original plan of SMUOS B? Who would help? Hands up.

**Comment by christoph-v** [comment]
Sun, 31st March, John C. and me had some discussion on x3d-public about possible content of a new network working group and of SP-ARK project.

I excerpted the discussion and added text files to the directory [https://github.com/christoph-v/spark/tree/master/3rd-party-input/yottzumm%40gmail.com](url)

**Comment by christoph-v** [comment]
John C.: What do you view as the primary SP-ARK actions?
1) SP-ARK is dedicated to the use (and support) of X3Dv4
2) basically, the playground is open to anybody, who is interested in simple multiuser scenes
3) probably we will implement some demo application maybe even a server (depends on support)
4) Goal 1: help the Web3D Consortium in defining an application layer protocol for the Network Sensor

8) SP-ARK has not been started yet, but with this e-mail the probability of a start increases :-)

**Comment by christoph-v** [comment]
All these brain stormings lead to phrasing version 0.1 of the project exposè  
https://github.com/christoph-v/spark/blob/master/3rd-party-input/esdp-bs/project-exposee_v0.1-2019-04-01.txt

**Comment by coderextreme** [comment]
Christoph, check out Nvidia’s Omniverse.  There are rumblings on GitHub
Sent from Mail for Windows 10

**Comment by christoph-v** [comment]
Which kind of rumblings?

**Comment by christoph-v** [comment]
Robert's comments (via E-Mail, German language)

Hallo
Ich schreibe Dir per email zurück:

Es sind wesentliche Begriffe nicht erklärt: „Network Sensor“ Node, SMS

Das Ziel des Projektes sollte schon irgendwie beschrieben sein, wie sollte man sonst wissen was man beim Projekt macht, oder anderes gesagt wird nicht erklärt worum es bei dem Projekt geht oder gemacht wird.

Was bedeutet Support of Standardization genauer?

Es gibt keinen offensichtlichen Zuammenhang zwischen den Zielen und dem (nicht beschrifteten) Bild

SP-Ark vs. SPARK

Es fehlt eine Legende zun dem Bild, was ist was?

Das Ziel ist die Unterstützung der Standardisierung des „Network Sensors“, im Bild sieht es so aus als würde SPARK aus Srr-Trains 0.01 version 1.0 machen

Mir fehlt eine Begründung wie Du vom formulierten Ziel auf SMS Biotope kommst

Ich verstehe es nicht 😊
Liebe Grüße

Robert

**Comment by christoph-v** [comment]
Having Robert's comments in mind, I have updated the homepage.

Now I would like to say thank you to Theo, who did the re-test.
He sent his comments via E-Mail (German language):

Hallo Christoph,
*)
A Simple Multiuser Scene is an X3Dv4***) MU Scene, which uses standardized communication protocols to communicate among scene instances and with a server.
**It uses the X3D Network Sensor Node(tbd.) to interface the network**

Letzten Satz verstehe ich nicht.
Sonst passt alles.
LG
Theo

**Comment by christoph-v** [comment]
Thx for the help. Home page is now ready.
